# Generated by Django 5.2.4 on 2025-08-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_room_remove_player_name_player_user_player_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='is_game_started',
            field=models.BooleanField(default=False),
        ),
    ]
